-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.7.0-rc9
-- Generated: 2019-12-06 05:57 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_snowplowanalytics_factotum_task_update_1 (
    "schema_vendor"               VARCHAR(128)     ENCODE ZSTD NOT NULL,
    "schema_name"                 VARCHAR(128)     ENCODE ZSTD NOT NULL,
    "schema_format"               VARCHAR(128)     ENCODE ZSTD NOT NULL,
    "schema_version"              VARCHAR(128)     ENCODE ZSTD NOT NULL,
    "root_id"                     CHAR(36)         ENCODE RAW  NOT NULL,
    "root_tstamp"                 TIMESTAMP        ENCODE ZSTD NOT NULL,
    "ref_root"                    VARCHAR(255)     ENCODE ZSTD NOT NULL,
    "ref_tree"                    VARCHAR(1500)    ENCODE ZSTD NOT NULL,
    "ref_parent"                  VARCHAR(255)     ENCODE ZSTD NOT NULL,
    "application_context.name"    VARCHAR(4096)    ENCODE ZSTD NOT NULL,
    "application_context.version" VARCHAR(4096)    ENCODE ZSTD NOT NULL,
    "factfile"                    VARCHAR(1000000) ENCODE ZSTD NOT NULL,
    "job_name"                    VARCHAR(4096)    ENCODE ZSTD NOT NULL,
    "job_reference"               VARCHAR(4096)    ENCODE ZSTD NOT NULL,
    "run_duration"                VARCHAR(4096)    ENCODE ZSTD NOT NULL,
    "run_reference"               VARCHAR(4096)    ENCODE ZSTD NOT NULL,
    "run_state"                   VARCHAR(9)       ENCODE ZSTD NOT NULL,
    "start_time"                  TIMESTAMP        ENCODE ZSTD NOT NULL,
    "tags"                        VARCHAR(4096)    ENCODE ZSTD NOT NULL,
    "task_states"                 VARCHAR(5000)    ENCODE ZSTD NOT NULL,
    "task_transitions"            VARCHAR(5000)    ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_snowplowanalytics_factotum_task_update_1 IS 'iglu:com.snowplowanalytics.factotum/task_update/jsonschema/1-0-0';
