-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.3.1
-- Generated: 2016-08-22 11:20

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_snowplowanalytics_snowplow_application_error_1 (
    "schema_vendor"        VARCHAR(128)  ENCODE ZSTD      NOT NULL,
    "schema_name"          VARCHAR(128)  ENCODE ZSTD      NOT NULL,
    "schema_format"        VARCHAR(128)  ENCODE ZSTD      NOT NULL,
    "schema_version"       VARCHAR(128)  ENCODE ZSTD      NOT NULL,
    "root_id"              CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"          TIMESTAMP     ENCODE ZSTD      NOT NULL,
    "ref_root"             VARCHAR(255)  ENCODE ZSTD      NOT NULL,
    "ref_tree"             VARCHAR(1500) ENCODE ZSTD      NOT NULL,
    "ref_parent"           VARCHAR(255)  ENCODE ZSTD      NOT NULL,
    "message"              VARCHAR(2048) ENCODE ZSTD      NOT NULL,
    "programming_language" VARCHAR(12)   ENCODE ZSTD      NOT NULL,
    "class_name"           VARCHAR(1024) ENCODE ZSTD,
    "exception_name"       VARCHAR(1024) ENCODE ZSTD,
    "is_fatal"             BOOLEAN       ENCODE RUNLENGTH,
    "line_number"          INT           ENCODE ZSTD,
    "stack_trace"          VARCHAR(8192) ENCODE ZSTD,
    "thread_id"            INT           ENCODE ZSTD,
    "thread_name"          VARCHAR(1024) ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_snowplowanalytics_snowplow_application_error_1 IS 'iglu:com.snowplowanalytics.snowplow/application_error/jsonschema/1-0-0';
