-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.7.0-rc9
-- Generated: 2019-12-06 05:43 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_snowplowanalytics_snowplow_ua_parser_context_1 (
    "schema_vendor"     VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_name"       VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_format"     VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_version"    VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "root_id"           CHAR(36)      ENCODE RAW  NOT NULL,
    "root_tstamp"       TIMESTAMP     ENCODE ZSTD NOT NULL,
    "ref_root"          VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "ref_tree"          VARCHAR(1500) ENCODE ZSTD NOT NULL,
    "ref_parent"        VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "device_family"     VARCHAR(4096) ENCODE ZSTD NOT NULL,
    "os_family"         VARCHAR(4096) ENCODE ZSTD NOT NULL,
    "useragent_family"  VARCHAR(4096) ENCODE ZSTD NOT NULL,
    "os_major"          VARCHAR(4096) ENCODE ZSTD,
    "os_minor"          VARCHAR(4096) ENCODE ZSTD,
    "os_patch"          VARCHAR(4096) ENCODE ZSTD,
    "os_patch_minor"    VARCHAR(4096) ENCODE ZSTD,
    "os_version"        VARCHAR(4096) ENCODE ZSTD,
    "useragent_major"   VARCHAR(4096) ENCODE ZSTD,
    "useragent_minor"   VARCHAR(4096) ENCODE ZSTD,
    "useragent_patch"   VARCHAR(4096) ENCODE ZSTD,
    "useragent_version" VARCHAR(4096) ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_snowplowanalytics_snowplow_ua_parser_context_1 IS 'iglu:com.snowplowanalytics.snowplow/ua_parser_context/jsonschema/1-0-0';
